# Generated by Django 4.0 on 2022-05-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_staffupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', models.FileField(null=True, upload_to='media/')),
            ],
        ),
    ]
