# Generated by Django 4.0 on 2022-05-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_staffdoc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffdoc',
            old_name='videos',
            new_name='videofile',
        ),
    ]
