# Generated by Django 4.0 on 2022-05-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffUpload',
        ),
    ]
