# Generated by Django 4.0 on 2022-05-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0007_rename_video_staffupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffdoc',
            old_name='videofile',
            new_name='docfile',
        ),
        migrations.AddField(
            model_name='staffdoc',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
