# Generated by Django 4.0 on 2022-05-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0008_rename_videofile_staffdoc_docfile_staffdoc_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffdoc',
            old_name='name',
            new_name='docname',
        ),
    ]
